version: '3.7'

services:

  mqtt-project:
    build: ../.
    container_name: mqtt-project
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://dbmqtt:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - dbmqtt
    networks:
      - my-network

  dbmqtt:
    image: postgres:15.2
    container_name: postgresqldbmqtt
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge